[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
buildArgs = ["DATABASE_URL=${{DATABASE_URL}}"]

[deploy]
startCommand = "./backend"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
